### ISSUE TITLE
Should have bold font discouragement/warnings.

### ISSUE THREAD

**Issue by kentfredric** [perlancar/perl-Dist-Zilla-Plugin-ShareDir-Clean#1]
I'm filing here because this doesn't have an existing RT queue yet.

But it should be said that shipping a dist that modifies the host environment directly in arbitrary ways without being safely marshalled through CPAN tools or EUMM should be considered moderately evil. 

Especially when it comes to `rm`.

Its probably not going to be a problem for any vendor who is smart enough to use `pure_install`, but it should be said that extreme caution needs to be taken here, because reaching outside your restricted install context and writing/deleting _outside_ DESTDIR=  at any point will get you shot by vendor tools/users.

For instance, directly reading/writing to outside DESTDIR in gentoo will have the vendor toolchains sandbox send perl a kill signal. 

Additionally, vendors like Gentoo have no need for this utility to be used in dists, because we already have a system to ensure share directories get removed for future installs. ( Because when version N is removed, all of version N's files are removed with it, intelligently, ... after version Y is installed, by noting which files Y installed and removing the files N installed that didn't get replaced by Y ).

So as well intentioned as this utility may be, it is very much not on even footing with File::ShareDir::Install, which only modifies the fake layout which then gets rolled out to DESTDIR= , anything that tries to un-pick them from $SITEPERLLIB is much, much more dangerous.

Such a change is desired collectively, however, I don't feel augmenting Makefile.PL directly is the right layer, and such a change is probably better suited as a first class EUMM feature, which is only turned on electively by various CPAN installers who consider that perl modules _should_ be allowed to delete arbitrary files from the host system.

**Comment by kentfredric** [comment]
Just for context: https://metacpan.org/pod/File::ShareDir::Install#delete_share  <-- even though this exists ... its basically a headless chicken that deletes an always empty dir.

https://rt.cpan.org/Ticket/Display.html?id=92084#txn-1324511

**Comment by perlancar** [comment]
Agreed about the warning/dangerous nature, I'll add it. Also agreed about the whole DZP:ShareDir::{Tarball,Clean} hack being unnecessary with the proper uninstall/upgrade feature (like one that exists in virtually every OS/linux package management).

Do you think the bit in Makefile.PL should add a check to skip if it detects running under Gentoo?

**Comment by kentfredric** [comment]
You could, but there is literally no standard you can use at present to detect a "Vendor Installer" or "Vendor Packager" context. That is, "running on a gentoo machine" is not enough, because you can have perlbrews that desire the CPAN installer path.

And you can't check for any specific traits of the installer software, because the Vendor Installer here is in fact, 3 separate systems, all simply implementing a common spec, and there are no defined guarantees about what to expect to see at the CPAN level to know.

I've been chatting with @ribasushi about getting some sort of ENV flag to allow vendors to signify alternative handling of issues, but its one of those standards things that needs a lot of thought.

For instance, my half assed ideas entail

``` bash
  VENDOR_QA_MODE=fatal
  VENDOR_QA_MODE=warn
  VENDOR_QA_MODE=none # 
```

For some things. But deletion of files should be marked on none of those.

```
    PERL_TOOLCHAIN_ATOMIC=1 
    PERL_NOINSTALLER_MAGIC=1
```

Or something. I don't know.

Lots of features are really needed in EU:I to bring things to a modern standard. 

( Like for instance, EUI should have a feature that prevents it from removing files owned by another distribution, but the requirements to make that doable are high )

**Comment by perlancar** [comment]
Closing this issue as I have added the bold warnings.
